apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teastore-recommender
spec:
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-recommender
    spec:
      nodeSelector:
        type: worker
      containers:
      - name: teastore-recommender
        image: descartesresearch/teastore-recommender
        ports:
        - containerPort: 8080
        env:
        - name: USE_POD_IP
          value: "true"
        - name: REGISTRY_HOST
          value: "teastore-registry"
        resources:
          requests:
            memory: "1Gi"
            cpu: "220m"
          limits:
            cpu: "2000m"
            memory: "3Gi"
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: "/tools.descartes.teastore.recommender/rest/train/isready"
            port: 8080
            scheme: HTTP